apiVersion: v1
kind: Service
metadata:
  name: mental-health-service
spec:
  type: NodePort
  selector:
    app: mental-health-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
